SELECT * FROM BOOK WHERE keyName = 1;
INSERT INTO BOOK VALUES("978-0-596-00920-4","Head First Java 2nd Edition","Kathy Sierra Bert Bates",26.07);
INSERT INTO BOOK VALUES("978-0-470-37174-3","Beginning Programming with Java For Dummies","Barry Burd",17.39);
INSERT INTO BOOK VALUES("0-321-35668-2","Effective Java 2nd Edition","Joshua Bloch",39.74);
INSERT INTO BOOK VALUES("978-0-071-60632-1","Java A Beginner's Guide 5th Edition","Herbert Schildt",24.52);
INSERT INTO BOOK VALUES("0-321-60378-4","Eclipse Rich Client Platform Second Edition","Jeff McAffer Jean-Michel Lemieux Chris Aniszczyk",37.75);
SELECT * FROM BOOK WHERE keyName = 0-321-60378-4;
SELECT * FROM BOOK WHERE keyName = 978-0-470-37174-9;
SELECT * FROM BOOK WHERE keyName = 978-0-071-60632-5;
SELECT * FROM BOOK WHERE keyName = 2;
SELECT * FROM BOOK WHERE keyName = 0-321-35668-3;


